
                   ###################################################################### 转换、检查、纠正基础数据字典（Info.field_base） 

20220309-11:07:46  field_base: 351行
20220309-11:07:46  删除95个available“不可用”字段：['dev_channel_name_teamzk', 'age_teamzk', 'sex_teamzk', 'stop_times_teamadd', 'resent_stop_date_teammax', 'monthsaready_resent_stop_date_teammax', 'is_real_name_teamzk', 'track_eff_date_teamzk', 'monthsaready_track_eff_date_teamzk', 'track_exp_date_teamzk', 'monthsremain_track_exp_date_teamzk', 'pack_hd_num_teamadd', 'point_teamzk', 'basic_credit_teamzk', 'quota_teamzk', 'is_lh_teamzk', 'lh_type_teamzk', 'bxl_flow_step_teamzk', 'bxl_deal_times_teamzk', 'is_deal_bxl_teamzk', 'pack_bxl_num_teamzk', 'owe_times_teamadd', 'last_owe_month_teammax', 'monthsaready_last_owe_month_teammax', 'payment_fee_teamzk', 'balance_teamadd', 'sms_fee_teamadd', 'is_shaungka_teamzk', 'shaungka_type_teamzk', 'ct_calling_dur_teamadd', 'ct_cnt_teamadd', 'ct_calling_cnt_teamadd', 'wj_calling_dur_teamadd', 'wj_cnt_teamadd', 'wj_calling_cnt_teamadd', 'jwq_num_teamadd', 'jwq_ct_num_teamadd', 'jwq_wj_num_teamadd', 'jwq_calling_num_teamadd', 'jwq_ct_calling_num_teamadd', 'jwq_wj_calling_num_teamadd', 'jwq_called_num_teamadd', 'jwq_ct_called_num_teamadd', 'jwq_wj_called_num_teamadd', 'last_to_acct_flux_teamzk', 'acct_to_next_flux_teamadd', 'int_flux_teamadd', 'int_flux_days_teammax', 'normal_flux_teamadd', 'normal_flux_days_teammax', 'normal_flux_days_teammax_p', 'night_flux_teamadd', 'night_flux_days_teammax', 'night_flux_days_teammax_p', 'self_scs_tsbz_cnt_teamadd', 'tyaddresscode_teamzk', 'tyaddressname_teamzk', 'dev_channel_name_k', 'area_no_k', 'age_k', 'sex_k', 'is_valid_k', 'stop_times_k', 'resent_stop_date_k', 'is_real_name_k', 'is_grp_member_k', 'prod_spec_name_k', 'is_comp_k', 'comp_user_no_k', 'comp_eff_date_k', 'comp_exp_date_k', 'comp_type_k', 'comp_num_k', 'comp_kd_num_k', 'comp_yd_num_k', 'comp_hd_num_k', 'pack_hd_num_k', 'point_k', 'star_k', 'basic_credit_k', 'quota_k', 'owe_flag_k', 'owe_charge_k', 'owe_times_k', 'owe_charge_acct_k', 'payment_fee_k', 'balance_k', 'is_qw_wifi_k', 'is_xygj_k', 'is_znms_k', 'is_tykj_k', 'is_jty_k', 'self_scs_cnt_k', 'self_com_cnt_k', 'valuecnt__is_valid_k~1']
20220309-11:07:46  field_base: 256行

20220309-11:07:46  删除10个基于“不可用”字段加工的手动衍生_py字段：
                                                         field_name                                            formula
                   80                                arpu_teamadd_p                     arpu_teamadd / balance_teamadd
                   151                      int_flux_days_teammax_p                 int_flux_days_teammax / days_month
                   176  add_prodspecfluw_packflowsum_lasttoacctflux  prod_spec_fluw_teamzk + pack_flow_sum_teamadd ...
                   179                         data_flux_teamadd_p3  data_flux_teamadd / add_prodspecfluw_packflows...
                   273              monthsaready_resent_stop_date_k                  current_date - resent_stop_date_k
                   289                 monthsaready_comp_eff_date_k                     current_date - comp_eff_date_k
                   291                 monthsremain_comp_exp_date_k                   comp_exp_date_k - current_date_k
                   317                                     arpu_k_p                                   arpu_k/balance_k
                   318                                  balance_k_p                          balance_k/prod_spec_fee_k
                   346                    paste_channel_prod_open_k  (monthsaready_open_date_k, dev_channel_nbr_k, ...
20220309-11:07:46  field_base: 246行
20220309-11:07:46  删除1个基于“不可用”字段加工的自动衍生_py字段：['valuecnt__is_valid_k~1']
20220309-11:07:46  field_base: 246行

                   ###################################################################### 加工训练账期近n月基础数据
                    
20220309-11:07:46  开始时间：2022-03-09 11:07:46
20220309-11:07:46  month: 202109
20220309-11:07:46  参数设置：
                       step: train
                       Info.model_name: 路由器潜客模型_融合
                       Info.n_recent: 3
                       drop_midtable: True
                       cover_table_all: False
                       Info.Pcase_limit: 10000
                       Info.traintable_ratio: 3
                       Info.Pcumsum_limit: nan
                       Info.timein_count: nan

                   ------------------------------------- 检查各前置表 --------------------------------------------------- 
20220309-11:07:46  检查 ml.dm_zc_rh_moxing_team_info_m


Traceback (most recent call last):
  File "D:\installdir_xj\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1586, in execute
    cur.execute(*args, **kwargs)
20220309-11:07:46  psycopg2.errors.UndefinedTable: 错误:  关系 "ml.dm_zc_rh_moxing_team_info_m" 不存在
                   LINE 1: ...ast(acct_month as text) acct_month, count(1) from ml.dm_zc_r...
                                                                                ^
20220309-11:07:46  
                   The above exception was the direct cause of the following exception:


Traceback (most recent call last):
  File "<ipython-input-3-f34e9a31e7d4>", line 29, in <module>
    base_train[model_name], Info = privy_basedatafun('train', Info, cover_table_all=Info.cover_table_all_train)
  File "D:\STUDY\Python\PycharmProjects\ModelProject\selfmodule\tablemodule\tablefun.py", line 447, in privy_basedatafun
    mlist_x = get_month_count(Info.table_x, Info.col_month, end=month)
  File "D:\STUDY\Python\PycharmProjects\ModelProject\selfmodule\toolmodule\datatrans.py", line 282, in get_month_count
    mlist = my_sql_fun(sql_mlist, method='read', index_col=col_month).sort_values(by=col_month)
  File "D:\STUDY\Python\PycharmProjects\ModelProject\selfmodule\toolmodule\datatrans.py", line 146, in my_sql_fun
    data_res = pd.read_sql(sql, conn1, index_col=index_col, **kwargs)
  File "D:\installdir_xj\Anaconda3\lib\site-packages\pandas\io\sql.py", line 412, in read_sql
    chunksize=chunksize,
  File "D:\installdir_xj\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1633, in read_query
    cursor = self.execute(*args)
  File "D:\installdir_xj\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1598, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'select cast(acct_month as text) acct_month, count(1) from ml.dm_zc_rh_moxing_team_info_m where cast(acct_month as text) <= '202109' group by acct_month': 错误:  关系 "ml.dm_zc_rh_moxing_team_info_m" 不存在
LINE 1: ...ast(acct_month as text) acct_month, count(1) from ml.dm_zc_r...
                                                             ^

