
                   ###################################################################### 转换、检查、纠正基础数据字典（Info.field_base） 

20220309-11:07:45  field_base: 334行
20220309-11:07:45  删除66个available“不可用”字段：['dev_channel_name_teamzk', 'age_teamzk', 'sex_teamzk', 'stop_times_teamadd', 'resent_stop_date_teammax', 'monthsaready_resent_stop_date_teammax', 'is_real_name_teamzk', 'track_eff_date_teamzk', 'monthsaready_track_eff_date_teamzk', 'track_exp_date_teamzk', 'monthsremain_track_exp_date_teamzk', 'pack_hd_num_teamadd', 'point_teamzk', 'basic_credit_teamzk', 'quota_teamzk', 'is_lh_teamzk', 'lh_type_teamzk', 'bxl_flow_step_teamzk', 'bxl_deal_times_teamzk', 'is_deal_bxl_teamzk', 'pack_bxl_num_teamzk', 'owe_times_teamadd', 'last_owe_month_teammax', 'monthsaready_last_owe_month_teammax', 'payment_fee_teamzk', 'balance_teamadd', 'sms_fee_teamadd', 'is_shaungka_teamzk', 'shaungka_type_teamzk', 'ct_calling_dur_teamadd', 'ct_cnt_teamadd', 'ct_calling_cnt_teamadd', 'wj_calling_dur_teamadd', 'wj_cnt_teamadd', 'wj_calling_cnt_teamadd', 'jwq_num_teamadd', 'jwq_ct_num_teamadd', 'jwq_wj_num_teamadd', 'jwq_calling_num_teamadd', 'jwq_ct_calling_num_teamadd', 'jwq_wj_calling_num_teamadd', 'jwq_called_num_teamadd', 'jwq_ct_called_num_teamadd', 'jwq_wj_called_num_teamadd', 'last_to_acct_flux_teamzk', 'acct_to_next_flux_teamadd', 'int_flux_teamadd', 'int_flux_days_teammax', 'normal_flux_teamadd', 'normal_flux_days_teammax', 'night_flux_teamadd', 'night_flux_days_teammax', 'self_scs_tsbz_cnt_teamadd', 'tyaddresscode_teamzk', 'tyaddressname_teamzk', 'market_time_teamzk', 'start_use_time_teamzk', 'end_use_time_teamzk', 'market_time_1_teamzk', 'start_use_time_1_teamzk', 'end_use_time_1_teamzk', 'rgst_tmn_time_2_teamzk', 'market_time_2_teamzk', 'start_use_time_2_teamzk', 'end_use_time_2_teamzk', 'pack_spcl_exp_date_teamzk']
20220309-11:07:45  field_base: 268行

20220309-11:07:45  删除7个基于“不可用”字段加工的手动衍生_py字段：
                                                         field_name                                            formula
                   80                                arpu_teamadd_p                     arpu_teamadd / balance_teamadd
                   151                      int_flux_days_teammax_p                 int_flux_days_teammax / days_month
                   156                   normal_flux_days_teammax_p              normal_flux_days_teammax / days_month
                   159                    night_flux_days_teammax_p               night_flux_days_teammax / days_month
                   176  add_prodspecfluw_packflowsum_lasttoacctflux  prod_spec_fluw_teamzk + pack_flow_sum_teamadd ...
                   179                         data_flux_teamadd_p3  data_flux_teamadd / add_prodspecfluw_packflows...
                   332              monthsremain_pack_spcl_exp_date           pack_spcl_exp_date_teamzk - current_date
20220309-11:07:45  field_base: 261行


D:\STUDY\Python\PycharmProjects\ModelProject\selfmodule\binarymodule\modelinfo.py:84: UserWarning: 确定下列日期类字段的into_model是否限制 ‘删除’：
                 field_name              comment into_model
280  rgst_tmn_time_1_teamzk  上一个终端_注册日期        NaN
  warnings.warn(s)

                   ###################################################################### 加工训练账期近n月基础数据
                    
20220309-11:07:45  开始时间：2022-03-09 11:07:45
20220309-11:07:45  month: 202109
20220309-11:07:45  参数设置：
                       step: train
                       Info.model_name: 副卡加装模型_移网
                       Info.n_recent: 3
                       drop_midtable: True
                       cover_table_all: False
                       Info.Pcase_limit: 10000
                       Info.traintable_ratio: 3
                       Info.Pcumsum_limit: nan
                       Info.timein_count: 50000

                   ------------------------------------- 检查各前置表 --------------------------------------------------- 
20220309-11:07:45  检查 ml.dm_zc_yw_moxing_team_info_m


Traceback (most recent call last):
  File "D:\installdir_xj\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1586, in execute
    cur.execute(*args, **kwargs)
20220309-11:07:45  psycopg2.errors.UndefinedTable: 错误:  关系 "ml.dm_zc_yw_moxing_team_info_m" 不存在
                   LINE 1: ...ast(acct_month as text) acct_month, count(1) from ml.dm_zc_y...
                                                                                ^
20220309-11:07:45  
                   The above exception was the direct cause of the following exception:


Traceback (most recent call last):
  File "<ipython-input-3-f34e9a31e7d4>", line 29, in <module>
    base_train[model_name], Info = privy_basedatafun('train', Info, cover_table_all=Info.cover_table_all_train)
  File "D:\STUDY\Python\PycharmProjects\ModelProject\selfmodule\tablemodule\tablefun.py", line 447, in privy_basedatafun
    mlist_x = get_month_count(Info.table_x, Info.col_month, end=month)
  File "D:\STUDY\Python\PycharmProjects\ModelProject\selfmodule\toolmodule\datatrans.py", line 282, in get_month_count
    mlist = my_sql_fun(sql_mlist, method='read', index_col=col_month).sort_values(by=col_month)
  File "D:\STUDY\Python\PycharmProjects\ModelProject\selfmodule\toolmodule\datatrans.py", line 146, in my_sql_fun
    data_res = pd.read_sql(sql, conn1, index_col=index_col, **kwargs)
  File "D:\installdir_xj\Anaconda3\lib\site-packages\pandas\io\sql.py", line 412, in read_sql
    chunksize=chunksize,
  File "D:\installdir_xj\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1633, in read_query
    cursor = self.execute(*args)
  File "D:\installdir_xj\Anaconda3\lib\site-packages\pandas\io\sql.py", line 1598, in execute
    raise ex from exc
pandas.io.sql.DatabaseError: Execution failed on sql 'select cast(acct_month as text) acct_month, count(1) from ml.dm_zc_yw_moxing_team_info_m where cast(acct_month as text) <= '202109' group by acct_month': 错误:  关系 "ml.dm_zc_yw_moxing_team_info_m" 不存在
LINE 1: ...ast(acct_month as text) acct_month, count(1) from ml.dm_zc_y...
                                                             ^

